### ISSUE TITLE
Missing file: GaiaCompiled_RV.txt

### ISSUE THREAD

**Issue by hybridherbst** [ageller/UnityGaiaHDRStarClusters#1]
Hi, I found this project while searching for Gaia <> Unity options.

While I get some star clusters to load, it seems there's at least one file missing which only has the meta file: GaiaCompiled_RV.txt, meta file is there: https://github.com/ageller/UnityGaiaHDRStarClusters/blob/master/Assets/Data/GaiaCompiled_RV.txt.meta

Would you be able to point me to where to get that file, or add it to the repo? Thanks!

**Comment by ageller** [comment]
Thanks for your interest in this.  Honestly, I had just used this repo as a backup for my files, so I didn't think hard about including all the necessary files for others to run it.  But I'm glad you've found it and plan to use it!  I uploaded that data file here: https://northwestern.box.com/s/2gjms93povvf25p6v4fawadu4asr1bmm 

And I also added a link pointing there in the README.
